services:
  blog:
    image: ghcr.io/jackyzha0/quartz:latest
    container_name: blog
    ports:
      - "127.0.0.1:27801:8080"
    volumes:
      - ./notes:/usr/src/app/content
      - ./quartz.config.ts:/usr/src/app/quartz.config.ts:ro
      - ./quartz.layout.ts:/usr/src/app/quartz.layout.ts:ro
      - ./abcjs.js:/usr/src/app/quartz/static/abcjs.js
      - ./Head.tsx:/usr/src/app/quartz/components/Head.tsx:ro
    restart: unless-stopped
    environment:
      - QUARTZ_MODE=dev
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDIR_INTERVAL=300
